// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO8ZGZIqNwrPltChGFXztic2aEf37qKbg',
    appId: '1:742093003971:web:4d1315fdf91e830c1b1676',
    messagingSenderId: '742093003971',
    projectId: 'ecommerce-11364',
    authDomain: 'ecommerce-11364.firebaseapp.com',
    storageBucket: 'ecommerce-11364.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO4jfR1DVcbYfZ9Ke6eHuja64MvdiTQMc',
    appId: '1:742093003971:android:82a8b7e7c6ea70b21b1676',
    messagingSenderId: '742093003971',
    projectId: 'ecommerce-11364',
    storageBucket: 'ecommerce-11364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-eI4u8W3Lu2dB-l3ADuNNp74hE1cgt0w',
    appId: '1:742093003971:ios:b72ac987bf5c256a1b1676',
    messagingSenderId: '742093003971',
    projectId: 'ecommerce-11364',
    storageBucket: 'ecommerce-11364.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-eI4u8W3Lu2dB-l3ADuNNp74hE1cgt0w',
    appId: '1:742093003971:ios:b72ac987bf5c256a1b1676',
    messagingSenderId: '742093003971',
    projectId: 'ecommerce-11364',
    storageBucket: 'ecommerce-11364.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO8ZGZIqNwrPltChGFXztic2aEf37qKbg',
    appId: '1:742093003971:web:9aa4c46f5b2045e41b1676',
    messagingSenderId: '742093003971',
    projectId: 'ecommerce-11364',
    authDomain: 'ecommerce-11364.firebaseapp.com',
    storageBucket: 'ecommerce-11364.appspot.com',
  );
}
